# Generated by Django 4.2.7 on 2023-12-01 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('part', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motorcycle',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.URLField(blank=True, default='')),
                ('category', models.CharField(choices=[('Turismo', 'Turismo'), ('Deportivo', 'Deportivo'), ('Naked', 'Naked'), ('Custom', 'Custom')], default='Custom', max_length=50)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('compatible_carroceria', models.ManyToManyField(related_name='compatible_carroceria', to='part.part')),
                ('compatible_chasis', models.ManyToManyField(related_name='compatible_chasis', to='part.part')),
                ('compatible_combustible', models.ManyToManyField(related_name='compatible_combustible', to='part.part')),
                ('compatible_frenos', models.ManyToManyField(related_name='compatible_frenos', to='part.part')),
                ('compatible_manillar', models.ManyToManyField(related_name='compatible_manillar', to='part.part')),
                ('compatible_motor', models.ManyToManyField(related_name='compatible_motor', to='part.part')),
                ('compatible_ruedas', models.ManyToManyField(related_name='compatible_ruedas', to='part.part')),
                ('compatible_suspension', models.ManyToManyField(related_name='compatible_suspension', to='part.part')),
                ('compatible_transmision', models.ManyToManyField(related_name='compatible_transmision', to='part.part')),
                ('selected_carrocería', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_carrocería', to='part.part')),
                ('selected_chasis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_chasis', to='part.part')),
                ('selected_combustible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_combustible', to='part.part')),
                ('selected_frenos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_frenos', to='part.part')),
                ('selected_manillar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_manillar', to='part.part')),
                ('selected_motor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_motor', to='part.part')),
                ('selected_ruedas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_ruedas', to='part.part')),
                ('selected_suspension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_suspension', to='part.part')),
                ('selected_transmision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_transmision', to='part.part')),
            ],
            bases=('product.product',),
        ),
        migrations.CreateModel(
            name='DerivedMotorcycle',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(default='Moto modificada', max_length=50)),
                ('base_motorcycle', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='base_motorcycle', to='motorcycle.motorcycle')),
                ('carroceria', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='carroceria', to='part.part')),
                ('chasis', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='chasis', to='part.part')),
                ('combustible', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='combustible', to='part.part')),
                ('frenos', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='frenos', to='part.part')),
                ('manillar', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='manillar', to='part.part')),
                ('motor', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='selemotor', to='part.part')),
                ('ruedas', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='ruedas', to='part.part')),
                ('suspension', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='suspension', to='part.part')),
                ('transmision', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='transmision', to='part.part')),
            ],
            bases=('product.product',),
        ),
    ]
