# Generated by Django 4.2.7 on 2023-12-01 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product.product')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.URLField(blank=True, default='')),
                ('category', models.CharField(choices=[('Carrocería', 'Carrocería'), ('Motor', 'Motor'), ('Transmisión', 'Transmisión'), ('Suspensión', 'Suspensión'), ('Ruedas', 'Ruedas'), ('Frenos', 'Frenos'), ('Manillar', 'Manillar'), ('Sistema de combustible', 'Sistema de combustible'), ('Chasis', 'Chasis')], max_length=50)),
                ('stock_quantity', models.PositiveIntegerField()),
            ],
            bases=('product.product',),
        ),
    ]
