# Generated by Django 4.2.7 on 2023-12-01 18:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmado', 'Confirmado'), ('Entregado', 'Entregado'), ('En reparto', 'En reparto')], default='pending', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shipment', models.CharField(choices=[('Recogida', 'Recogida'), ('Envío a domicilio', 'Envío a domicilio')], default='pickup', max_length=50)),
                ('address', models.CharField(max_length=255, null=True)),
                ('payment', models.CharField(choices=[('Contrarrembolso', 'Contrarrembolso'), ('Tarjeta', 'Tarjeta')], default='cash', max_length=50)),
                ('buyer_mail', models.EmailField(default='a@a.com', max_length=254)),
                ('buyer_name', models.CharField(default='a', max_length=50)),
                ('buyer_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(default='a', max_length=50)),
                ('postal_code', models.CharField(default='41720', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
