# Generated by Django 4.2.7 on 2023-12-01 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturers', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=15, unique=True)),
                ('product_type', models.CharField(choices=[('M', 'Motorcycle'), ('P', 'Part'), ('C', 'Configured')], max_length=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer', to='manufacturers.manufacturer')),
            ],
        ),
    ]
