# Generated by Django 4.2.7 on 2023-12-01 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=15, unique=True)),
                ('product_type', models.CharField(choices=[('M', 'Motorcycle'), ('P', 'Part'), ('C', 'Configured')], max_length=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
