from django.test import TestCase

import time
import json
import os
import requests
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from django.contrib.staticfiles.testing import StaticLiveServerTestCase
from selenium.webdriver.chrome.service import Service
from django.core.management import call_command
from selenium.webdriver.support import expected_conditions as EC

class TestTestadminproduct(TestCase):
    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls.driver = webdriver.Firefox()
        cls.driver.implicitly_wait(3)

    @classmethod
    def tearDownClass(cls):
        cls.driver.quit()
        super().tearDownClass()

    def setUp(self):
        call_command('loaddata', 'populate.json')

    def test_adminproduct(self):
        self.driver.get('http://localhost:8000/')
        self.driver.set_window_size(1695, 1087)

        
        self.driver.find_element(By.LINK_TEXT, "Registrarse").click()
        self.driver.find_element(By.ID, "email").clear()
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys("pepe@pepe.com")
        self.driver.find_element(By.ID, "password").clear()
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("1111@ñtR")
        self.driver.find_element(By.ID, "full_name").clear()
        self.driver.find_element(By.ID, "full_name").click()
        self.driver.find_element(By.ID, "full_name").send_keys("pepito pepe pepón")
        self.driver.find_element(By.ID, "phone").clear()
        self.driver.find_element(By.ID, "phone").click()
        self.driver.find_element(By.ID, "phone").send_keys("123456789")
        self.driver.find_element(By.ID, "address").send_keys("Vivo en mi casa")
        self.driver.find_element(By.CSS_SELECTOR, ".submit > .btn").click()
        self.driver.find_element(By.LINK_TEXT, "Iniciar Sesión").click()
        self.driver.find_element(By.ID, "email").clear()
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys("pepe@pepe.com")
        self.driver.find_element(By.ID, "password").clear()
        self.driver.find_element(By.ID, "password").send_keys(Keys.ENTER)
        self.driver.find_element(By.ID, "password").send_keys("1111@ñtR")
        self.driver.find_element(By.CSS_SELECTOR, ".submit > .btn").click()
        '''
        self.driver.find_element(By.LINK_TEXT, "Más detalles").click()
        self.driver.find_element(By.CSS_SELECTOR, ".qtyplus").click()
        self.driver.find_element(By.CSS_SELECTOR, ".round-black-btn:nth-child(5)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(2)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".navbar > a:nth-child(1) > img").click()
        self.driver.find_element(By.CSS_SELECTOR, ".item:nth-child(1) .col-sm-4:nth-child(2) .sin-estilo").click()
        self.driver.find_element(By.ID, "quantityInputPart").send_keys("2")
        self.driver.find_element(By.ID, "quantityInputPart").click()
        self.driver.find_element(By.CSS_SELECTOR, ".glyphicon-refresh").click()
        self.driver.find_element(By.LINK_TEXT, "Finalizar").click()
        self.driver.find_element(By.NAME, "city").click()
        self.driver.find_element(By.NAME, "city").send_keys("xx")
        self.driver.find_element(By.NAME, "postal_code").click()
        self.driver.find_element(By.NAME, "postal_code").send_keys("67891")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
        self.driver.find_element(By.LINK_TEXT, "Bienvenido, pepito pepe pepón").click()
        self.driver.find_element(By.CSS_SELECTOR, ".sin-estilo").click()
        
        self.driver.find_element(By.CSS_SELECTOR, ".item:nth-child(1) .col-sm-4:nth-child(2) .sin-estilo").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn-danger:nth-child(3)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".navbar > a:nth-child(1) > img").click()
        self.driver.find_element(By.CSS_SELECTOR, ".item:nth-child(1) .col-sm-4:nth-child(2) .sin-estilo").click()
        self.driver.find_element(By.LINK_TEXT, "Finalizar").click()
        self.driver.find_element(By.ID, "payment_method").click()
        dropdown = self.driver.find_element(By.ID, "payment_method")
        dropdown.find_element(By.XPATH, "//option[. = 'Tarjeta']").click()
        self.driver.find_element(By.CSS_SELECTOR, "#payment_method > option:nth-child(2)").click()
        self.driver.find_element(By.NAME, "email").click()
        self.driver.find_element(By.NAME, "email").send_keys("jose@jose.com")
        self.driver.find_element(By.NAME, "full_name").send_keys("joselillo")
        self.driver.find_element(By.NAME, "phone").send_keys("789678678")
        self.driver.find_element(By.NAME, "city").send_keys("sevilla")
        self.driver.find_element(By.NAME, "postal_code").send_keys("12678")
        self.driver.find_element(By.NAME, "address").send_keys("mi casa")
        self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(9)").click()
        WebDriverWait(self.driver, 20).until(EC.visibility_of_element_located((By.ID, "email")))
        self.driver.find_element(By.ID, "email").clear()
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys("sb-k43ebi28280380@personal.example.com")
        self.driver.find_element(By.ID, "btnNext").click()
        WebDriverWait(self.driver, 20).until(EC.visibility_of_element_located((By.ID, "password")))
        self.driver.find_element(By.ID, "password").clear()
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("nNU<<9Y%")
        self.driver.find_element(By.ID, "btnLogin").click()
        WebDriverWait(self.driver, 20).until(EC.visibility_of_element_located((By.ID, "payment-submit-btn")))
        self.driver.find_element(By.ID, "payment-submit-btn").click()
        WebDriverWait(self.driver, 5)
        self.driver.find_element(By.CSS_SELECTOR, ".navbar > a:nth-child(1) > img").click()
        self.driver.find_element(By.CSS_SELECTOR, ".categoria-img > img").click()
        self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) img").click()
        self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(3) img").click()
        self.driver.find_element(By.CSS_SELECTOR, ".col-sm-4:nth-child(2) .separator .hidden-sm").click()
        self.driver.find_element(By.CSS_SELECTOR, ".navbar > a:nth-child(1) > img").click()
        self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) img").click()
        self.driver.find_element(By.CSS_SELECTOR, ".items-row:nth-child(1) > .col-sm-4:nth-child(2) .separator .hidden-sm").click()
        self.driver.find_element(By.ID, "review-tab").click()
        self.driver.find_element(By.CSS_SELECTOR, ".navbar > a:nth-child(1) > img").click()
        self.driver.find_element(By.CSS_SELECTOR, ".categoria-img > img").click()
        self.driver.find_element(By.LINK_TEXT, "Más detalles").click()
        self.driver.find_element(By.ID, "review-tab").click()
        self.driver.find_element(By.LINK_TEXT, "Piezas de la moto").click()
        self.driver.find_element(By.NAME, "query").click()
        self.driver.find_element(By.NAME, "query").send_keys("ducati")
        self.driver.find_element(By.NAME, "query").send_keys(Keys.ENTER)
        '''


        self.driver.get('http://localhost:8000/')
        self.driver.find_element(By.LINK_TEXT, "Iniciar Sesión").click()
        self.driver.find_element(By.ID, "email").send_keys("admin@admin.com")
        self.driver.find_element(By.ID, "password").send_keys("1111@ñtR")
        self.driver.find_element(By.CSS_SELECTOR, ".submit > .btn").click()
        self.driver.find_element(By.LINK_TEXT, "Bienvenido, Admin").click()
        self.driver.find_element(By.CSS_SELECTOR, ".fa-laptop").click()
        self.driver.find_element(By.LINK_TEXT, "Administrar productos").click()
        self.driver.find_element(By.LINK_TEXT, "Ducati Panigale V4").click()
        self.driver.find_element(By.LINK_TEXT, "Editar motocicleta").click()
        self.driver.find_element(By.ID, "stock").click()
        self.driver.find_element(By.ID, "stock").send_keys("10")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
        self.driver.find_element(By.LINK_TEXT, "Carrocería de turismo").click()
        self.driver.find_element(By.LINK_TEXT, "Editar pieza").click()
        self.driver.find_element(By.ID, "price").click()
        self.driver.find_element(By.ID, "price").send_keys("20")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
        self.driver.find_element(By.LINK_TEXT, "Añadir pieza").click()
        self.driver.find_element(By.ID, "name").click()
        self.driver.find_element(By.ID, "name").send_keys("Nueva Pieza")
        self.driver.find_element(By.ID, "imagen").click()
        self.driver.find_element(By.ID, "imagen").send_keys("h")
        self.driver.find_element(By.ID, "imagen").send_keys(Keys.DOWN)
        self.driver.find_element(By.ID, "imagen").send_keys("https://www.jornadaperfecta.com/blog/wp-content/uploads/2022/09/Fekir2223b.jpeg")
        self.driver.find_element(By.ID, "category").click()
        dropdown = self.driver.find_element(By.ID, "category")
        dropdown.find_element(By.XPATH, "//option[. = 'Motor']").click()
        self.driver.find_element(By.CSS_SELECTOR, "#category > option:nth-child(2)").click()
        self.driver.find_element(By.ID, "stock").click()
        self.driver.find_element(By.ID, "stock").send_keys("10")
        self.driver.find_element(By.ID, "price").click()
        self.driver.find_element(By.ID, "price").send_keys("8000000")
        self.driver.find_element(By.ID, "manufacturer").click()
        dropdown = self.driver.find_element(By.ID, "manufacturer")
        dropdown.find_element(By.XPATH, "//option[. = 'Honda']").click()
        self.driver.find_element(By.CSS_SELECTOR, "#manufacturer > option:nth-child(3)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
        self.driver.find_element(By.LINK_TEXT, "Añadir moto").click()
        self.driver.find_element(By.ID, "name").click()
        self.driver.find_element(By.ID, "name").send_keys("nueva moto")
        self.driver.find_element(By.ID, "imagen").click()
        self.driver.find_element(By.ID, "imagen").click()
        self.driver.find_element(By.ID, "imagen").send_keys("https://www.jornadaperfecta.com/blog/wp-content/uploads/2022/09/Fekir2223b.jpeg")
        self.driver.find_element(By.ID, "category").click()
        dropdown = self.driver.find_element(By.ID, "category")
        dropdown.find_element(By.XPATH, "//option[. = 'Deportivo']").click()
        self.driver.find_element(By.CSS_SELECTOR, "#category > option:nth-child(2)").click()
        self.driver.find_element(By.ID, "stock").click()
        self.driver.find_element(By.ID, "stock").click()
        self.driver.find_element(By.ID, "stock").send_keys("80")
        self.driver.find_element(By.ID, "price").click()
        self.driver.find_element(By.ID, "price").send_keys("9000000")
        self.driver.find_element(By.ID, "manufacturer").click()
        dropdown = self.driver.find_element(By.ID, "manufacturer")
        dropdown.find_element(By.XPATH, "//option[. = 'Yamaha']").click()
        self.driver.find_element(By.CSS_SELECTOR, "#manufacturer > option:nth-child(4)").click()
        self.driver.find_element(By.ID, "part_2").click()
        self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(9) #part_2").click()
        self.driver.find_element(By.NAME, "carroceriac").click()
        self.driver.find_element(By.ID, "part_5").click()
        self.driver.find_element(By.NAME, "motorc").click()
        self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(11) #part_6").click()
        self.driver.find_element(By.ID, "part_8").click()
        self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(13) > .form-check:nth-child(2)").click()
        self.driver.find_element(By.NAME, "transmisionc").click()
        self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(13) #part_9").click()
        self.driver.find_element(By.ID, "part_12").click()
        self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(15) #part_12").click()
        self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(15) #part_13").click()
        self.driver.find_element(By.ID, "part_16").click()
        self.driver.find_element(By.NAME, "ruedac").click()
        self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(17) #part_17").click()
        self.driver.find_element(By.ID, "part_19").click()
        self.driver.find_element(By.NAME, "frenoc").click()
        self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(19) #part_20").click()
        self.driver.find_element(By.ID, "part_22").click()
        self.driver.find_element(By.NAME, "manillarc").click()
        self.driver.find_element(By.ID, "part_25").click()
        self.driver.find_element(By.NAME, "combustiblec").click()
        self.driver.find_element(By.ID, "part_28").click()
        self.driver.find_element(By.NAME, "chasisc").click()
        self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(25) #part_29").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
        self.driver.find_element(By.LINK_TEXT, "Bienvenido, Admin").click()
        self.driver.find_element(By.CSS_SELECTOR, ".sin-estilo").click()
        self.driver.find_element(By.LINK_TEXT, "Registrarse").click()
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys("antonio@antonio.com")
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("1111@ñtR")
        self.driver.find_element(By.ID, "full_name").click()
        self.driver.find_element(By.ID, "full_name").click()
        self.driver.find_element(By.ID, "full_name").send_keys("Antonio")
        self.driver.find_element(By.ID, "phone").click()
        self.driver.find_element(By.ID, "phone").send_keys("999999999")
        self.driver.find_element(By.ID, "address").click()
        self.driver.find_element(By.ID, "address").send_keys("La casa de antonio")
        self.driver.find_element(By.CSS_SELECTOR, ".submit > .btn").click()
        self.driver.find_element(By.LINK_TEXT, "Iniciar Sesión").click()
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys("antonio@antonio.com")
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("1111@ñtR")
        self.driver.find_element(By.CSS_SELECTOR, ".submit > .btn").click()
        WebDriverWait(self.driver, 20).until(EC.visibility_of_element_located((By.CSS_SELECTOR, ".footer-col li:nth-child(2) > a")))
        self.driver.find_element(By.CSS_SELECTOR, ".footer-col li:nth-child(2) > a").click()
        self.driver.find_element(By.LINK_TEXT, "Añadir Reclamación").click()
        self.driver.find_element(By.ID, "title").click()
        self.driver.find_element(By.ID, "title").send_keys("Mi pedido xxxxx no me ha llegado")
        self.driver.find_element(By.ID, "description").click()
        self.driver.find_element(By.ID, "description").send_keys("Hace unos diez dias que hice el pedido xxxxx y todavia no me lo habeis enviado")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
        self.driver.find_element(By.LINK_TEXT, "Bienvenido, Antonio").click()
        self.driver.find_element(By.CSS_SELECTOR, "#logoutForm > .sin-estilo").click()
        self.driver.find_element(By.LINK_TEXT, "Iniciar Sesión").click()
        self.driver.find_element(By.ID, "email").send_keys("admin@admin.com")
        self.driver.find_element(By.ID, "password").send_keys("1111@ñtR")
        self.driver.find_element(By.CSS_SELECTOR, ".submit > .btn").click()
        self.driver.find_element(By.LINK_TEXT, "Bienvenido, Admin").click()
        self.driver.find_element(By.CSS_SELECTOR, ".fa-laptop").click()
        self.driver.find_element(By.LINK_TEXT, "Administrar reclamaciones").click()
        self.driver.find_element(By.LINK_TEXT, "Responder").click()
        self.driver.find_element(By.NAME, "response_text").click()
        self.driver.find_element(By.NAME, "response_text").send_keys("Ni te va a llegar")
        self.driver.find_element(By.CSS_SELECTOR, ".float-right").click()
        self.driver.find_element(By.LINK_TEXT, "Bienvenido, Admin").click()
        self.driver.find_element(By.CSS_SELECTOR, ".sin-estilo").click()
        self.driver.find_element(By.LINK_TEXT, "Iniciar Sesión").click()
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys("antonio@antonio.com")
        self.driver.find_element(By.ID, "password").send_keys("1111@ñtR")
        self.driver.find_element(By.CSS_SELECTOR, ".submit > .btn").click()
        self.driver.find_element(By.CSS_SELECTOR, ".footer-col li:nth-child(2) > a").click()
        self.driver.find_element(By.LINK_TEXT, "Ver Respuesta").click()
        self.driver.find_element(By.LINK_TEXT, "Volver a la lista de reclamaciones").click()
        self.driver.find_element(By.LINK_TEXT, "Bienvenido, Antonio").click()
        self.driver.find_element(By.CSS_SELECTOR, "#logoutForm > .sin-estilo").click()
        
        self.driver.find_element(By.LINK_TEXT, "Iniciar Sesión").click()
        self.driver.find_element(By.ID, "email").send_keys("admin@admin.com")
        self.driver.find_element(By.ID, "password").send_keys("1111@ñtR")
        self.driver.find_element(By.CSS_SELECTOR, ".submit > .btn").click()
        self.driver.find_element(By.LINK_TEXT, "Bienvenido, Admin").click()
        self.driver.find_element(By.LINK_TEXT, "Administrar").click()
        self.driver.find_element(By.LINK_TEXT, "Información sobre las ventas").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(2)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(3)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(4)").click()
        self.driver.find_element(By.LINK_TEXT, "Bienvenido, Admin").click()
        self.driver.find_element(By.CSS_SELECTOR, ".sin-estilo").click()
        
        self.driver.find_element(By.LINK_TEXT, "Iniciar Sesión").click()
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys("antonio@antonio.com")
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("1111@ñtR")
        self.driver.find_element(By.CSS_SELECTOR, ".submit > .btn").click()
        self.driver.find_element(By.CSS_SELECTOR, ".item:nth-child(1) .col-sm-4:nth-child(2) .sin-estilo").click()
        self.driver.find_element(By.LINK_TEXT, "Finalizar").click()
        self.driver.find_element(By.NAME, "city").click()
        self.driver.find_element(By.NAME, "city").send_keys("mi cuidad")
        self.driver.find_element(By.NAME, "postal_code").click()
        self.driver.find_element(By.NAME, "postal_code").send_keys("78092")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
        self.driver.find_element(By.LINK_TEXT, "Bienvenido, Antonio").click()
        self.driver.find_element(By.CSS_SELECTOR, ".sin-estilo").click()
        self.driver.find_element(By.LINK_TEXT, "Iniciar Sesión").click()
        self.driver.find_element(By.ID, "email").send_keys("admin@admin.com")
        self.driver.find_element(By.ID, "password").send_keys("1111@ñtR")
        self.driver.find_element(By.CSS_SELECTOR, ".submit > .btn").click()
        self.driver.find_element(By.LINK_TEXT, "Bienvenido, Admin").click()
        self.driver.find_element(By.CSS_SELECTOR, ".fa-laptop").click()
        self.driver.find_element(By.LINK_TEXT, "Administrar pedidos").click()
        self.driver.find_element(By.XPATH, "//table/tbody/tr[1]/td[1]/a").click()
        self.driver.find_element(By.ID, "estado").click()
        dropdown = self.driver.find_element(By.ID, "estado")
        dropdown.find_element(By.XPATH, "//option[. = 'Confirmado']").click()
        self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(2)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
        self.driver.find_element(By.LINK_TEXT, "Bienvenido, Admin").click()
        self.driver.find_element(By.CSS_SELECTOR, ".sin-estilo").click()

            