from django.test import TestCase

import time
import json
import os
import requests
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from django.contrib.staticfiles.testing import StaticLiveServerTestCase
from selenium.webdriver.chrome.service import Service
from django.core.management import call_command
from selenium.webdriver.support import expected_conditions as EC

class TestTestadminproduct(TestCase):
    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls.driver = webdriver.Firefox()
        cls.driver.implicitly_wait(3)

    @classmethod
    def tearDownClass(cls):
        cls.driver.quit()
        super().tearDownClass()

    def setUp(self):
        call_command('loaddata', 'populate.json')

    def test_adminproduct(self):
        self.driver.get('http://localhost:8000/')
        self.driver.set_window_size(1695, 1087)      
        self.driver.find_element(By.LINK_TEXT, "Registrarse").click()
        self.driver.find_element(By.ID, "email").clear()
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys("pepe@pepe.com")
        self.driver.find_element(By.ID, "password").clear()
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("1111@ñtR")
        self.driver.find_element(By.ID, "full_name").clear()
        self.driver.find_element(By.ID, "full_name").click()
        self.driver.find_element(By.ID, "full_name").send_keys("pepito pepe pepón")
        self.driver.find_element(By.ID, "phone").clear()
        self.driver.find_element(By.ID, "phone").click()
        self.driver.find_element(By.ID, "phone").send_keys("123456789")
        self.driver.find_element(By.ID, "postal_code").clear()
        self.driver.find_element(By.ID, "postal_code").click()
        self.driver.find_element(By.ID, "postal_code").send_keys("12345")
        self.driver.find_element(By.ID, "city").clear()
        self.driver.find_element(By.ID, "city").click()
        self.driver.find_element(By.ID, "city").send_keys("Mi ciudad")
        self.driver.find_element(By.ID, "address").send_keys("Vivo en mi casa")
        self.driver.find_element(By.CSS_SELECTOR, ".submit > .btn").click()
        self.driver.find_element(By.LINK_TEXT, "Iniciar Sesión").click()
        self.driver.find_element(By.ID, "email").clear()
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys("pepe@pepe.com")
        self.driver.find_element(By.ID, "password").clear()
        self.driver.find_element(By.ID, "password").send_keys(Keys.ENTER)
        self.driver.find_element(By.ID, "password").send_keys("1111@ñtR")
        self.driver.find_element(By.CSS_SELECTOR, ".submit > .btn").click()

        self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) img").click()
        self.driver.find_element(By.LINK_TEXT, "Más detalles").click()
        self.driver.find_element(By.CSS_SELECTOR, ".round-black-btn").click()
        self.driver.find_element(By.ID, "quantityInputPart").click()
        self.driver.find_element(By.ID, "quantityInputPart").send_keys("1000")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-info").click()
        self.driver.find_element(By.CSS_SELECTOR, ".glyphicon-trash").click()
        self.driver.find_element(By.CSS_SELECTOR, ".navbar > a > img").click()
        self.driver.find_element(By.CSS_SELECTOR, ".categoria-img > img").click()
        self.driver.find_element(By.LINK_TEXT, "Más detalles").click()
        self.driver.find_element(By.CSS_SELECTOR, ".round-black-btn:nth-child(4)").click()
        self.driver.find_element(By.LINK_TEXT, "Finalizar").click()
        self.driver.find_element(By.ID, "payment_method").click()
        dropdown = self.driver.find_element(By.ID, "payment_method")
        dropdown.find_element(By.XPATH, "//option[. = 'Tarjeta']").click()
        self.driver.find_element(By.CSS_SELECTOR, "#payment_method > option:nth-child(2)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
        WebDriverWait(self.driver, 20).until(EC.visibility_of_element_located((By.ID, "email")))
        self.driver.find_element(By.ID, "email").clear()
        self.driver.find_element(By.ID, "email").click()
        self.driver.find_element(By.ID, "email").send_keys("sb-k43ebi28280380@personal.example.com")
        self.driver.find_element(By.ID, "btnNext").click()
        WebDriverWait(self.driver, 20).until(EC.visibility_of_element_located((By.ID, "password")))
        self.driver.find_element(By.ID, "password").clear()
        self.driver.find_element(By.ID, "password").click()
        self.driver.find_element(By.ID, "password").send_keys("nNU<<9Y%")
        self.driver.find_element(By.ID, "btnLogin").click()
        WebDriverWait(self.driver, 20).until(EC.visibility_of_element_located((By.ID, "payment-submit-btn")))
        self.driver.find_element(By.ID, "payment-submit-btn").click()
        WebDriverWait(self.driver, 20)
        self.driver.find_element(By.CSS_SELECTOR, ".navbar > a > img").click()
        self.driver.find_element(By.CSS_SELECTOR, ".categoria-img").click()
        self.driver.find_element(By.LINK_TEXT, "Más detalles").click()
        self.driver.find_element(By.LINK_TEXT, "Configurar a medida").click()
        self.driver.find_element(By.NAME, "carroceria").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
        self.driver.find_element(By.ID, "quantityInputPart").click()
        self.driver.find_element(By.ID, "quantityInputPart").send_keys("300")
        self.driver.find_element(By.CSS_SELECTOR, ".glyphicon-refresh").click()
        self.driver.find_element(By.LINK_TEXT, "Finalizar").click()
        self.driver.find_element(By.ID, "payment_method").click()
        dropdown = self.driver.find_element(By.ID, "payment_method")
        dropdown.find_element(By.XPATH, "//option[. = 'Contrarrembolso']").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
        self.driver.find_element(By.CSS_SELECTOR, ".navbar > a > img").click()
        self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(3) img").click()
        self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(2) img").click()
        self.driver.find_element(By.CSS_SELECTOR, ".categoria-img > img").click()
        self.driver.find_element(By.NAME, "query").click()
        self.driver.find_element(By.LINK_TEXT, "Más detalles").click()
        self.driver.find_element(By.CSS_SELECTOR, ".navbar > a > img").click()
        self.driver.find_element(By.LINK_TEXT, "Más detalles").click()
        self.driver.find_element(By.CSS_SELECTOR, ".stars > .fa-solid:nth-child(5)").click()
        self.driver.find_element(By.ID, "desccription").click()
        self.driver.find_element(By.ID, "desccription").send_keys("Muy bueno")
        self.driver.find_element(By.CSS_SELECTOR, ".round-black-btn-opinion").click()
        self.driver.find_element(By.LINK_TEXT, "Bienvenido, pepito pepe pepón").click()
        self.driver.find_element(By.LINK_TEXT, "Perfil").click()
        self.driver.find_element(By.ID, "id_full_name").click()
        self.driver.find_element(By.ID, "id_full_name").clear()
        self.driver.find_element(By.ID, "id_full_name").send_keys("jjjjjjj2")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
        self.driver.find_element(By.LINK_TEXT, "Bienvenido, jjjjjjj2").click()
        self.driver.find_element(By.LINK_TEXT, "Mis Pedidos").click()
        self.driver.find_element(By.LINK_TEXT, "Ver detalles").click()
        self.driver.find_element(By.CSS_SELECTOR, ".footer-col li:nth-child(2) > a").click()
        self.driver.find_element(By.LINK_TEXT, "Añadir Reclamación").click()
        self.driver.find_element(By.ID, "title").click()
        self.driver.find_element(By.ID, "title").send_keys("Mi reclamación")
        self.driver.find_element(By.ID, "description").click()
        self.driver.find_element(By.ID, "description").send_keys("Me quejo porque me gusta quejarme")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
        self.driver.find_element(By.LINK_TEXT, "Bienvenido, jjjjjjj2").click()
        self.driver.find_element(By.CSS_SELECTOR, ".sin-estilo").click()

        

        self.driver.find_element(By.LINK_TEXT, "Iniciar Sesión").click()
        self.driver.find_element(By.ID, "email").send_keys("admin@admin.com")
        self.driver.find_element(By.ID, "password").send_keys("1111@ñtR")
        self.driver.find_element(By.CSS_SELECTOR, ".submit > .btn").click()

        self.driver.find_element(By.LINK_TEXT, "Bienvenido, Admin").click()
        self.driver.find_element(By.LINK_TEXT, "Administrar").click()
        self.driver.find_element(By.LINK_TEXT, "Administrar pedidos").click()
        self.driver.find_element(By.XPATH, "//table/tbody/tr[1]/td[1]/a").click()
        self.driver.find_element(By.ID, "estado").click()
        dropdown = self.driver.find_element(By.ID, "estado")
        dropdown.find_element(By.XPATH, "//option[. = 'En reparto']").click()
        self.driver.find_element(By.CSS_SELECTOR, "option:nth-child(3)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
        self.driver.find_element(By.LINK_TEXT, "Bienvenido, Admin").click()
        self.driver.find_element(By.LINK_TEXT, "Administrar").click()
        self.driver.find_element(By.LINK_TEXT, "Administrar reclamaciones").click()
        self.driver.find_element(By.LINK_TEXT, "Bienvenido, Admin").click()
        self.driver.find_element(By.LINK_TEXT, "Administrar").click()
        self.driver.find_element(By.LINK_TEXT, "Información sobre las ventas").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(2)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(3)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn:nth-child(4)").click()
        self.driver.find_element(By.LINK_TEXT, "Bienvenido, Admin").click()
        self.driver.find_element(By.LINK_TEXT, "Administrar").click()
        self.driver.find_element(By.LINK_TEXT, "Administrar clientes").click()
        self.driver.find_element(By.NAME, "action").click()
        self.driver.find_element(By.NAME, "action").click()
        self.driver.find_element(By.LINK_TEXT, "Bienvenido, Admin").click()
        self.driver.find_element(By.LINK_TEXT, "Administrar").click()
        self.driver.find_element(By.LINK_TEXT, "Administrar productos").click()
        self.driver.find_element(By.LINK_TEXT, "Añadir pieza").click()
        self.driver.find_element(By.ID, "name").click()
        self.driver.find_element(By.ID, "name").send_keys("la pieza")
        self.driver.find_element(By.ID, "imagen").click()
        self.driver.find_element(By.ID, "imagen").send_keys("https://www.jornadaperfecta.com/blog/wp-content/uploads/2022/09/Fekir2223b.jpeg")
        self.driver.find_element(By.ID, "stock").click()
        self.driver.find_element(By.ID, "stock").send_keys("5000")
        self.driver.find_element(By.ID, "price").click()
        self.driver.find_element(By.ID, "price").send_keys("5000")
        self.driver.find_element(By.ID, "manufacturer").click()
        dropdown = self.driver.find_element(By.ID, "manufacturer")
        dropdown.find_element(By.XPATH, "//option[. = 'Ducati']").click()
        self.driver.find_element(By.CSS_SELECTOR, "#manufacturer > option:nth-child(2)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
        self.driver.find_element(By.LINK_TEXT, "Añadir moto").click()
        self.driver.find_element(By.ID, "name").click()
        self.driver.find_element(By.ID, "name").send_keys("producto")
        self.driver.find_element(By.ID, "imagen").click()
        self.driver.find_element(By.ID, "imagen").send_keys("https://www.jornadaperfecta.com/blog/wp-content/uploads/2022/09/Fekir2223b.jpeg")
        self.driver.find_element(By.ID, "category").click()
        dropdown = self.driver.find_element(By.ID, "category")
        dropdown.find_element(By.XPATH, "//option[. = 'Deportivo']").click()
        self.driver.find_element(By.CSS_SELECTOR, "#category > option:nth-child(2)").click()
        self.driver.find_element(By.ID, "stock").click()
        self.driver.find_element(By.ID, "stock").send_keys("90")
        self.driver.find_element(By.ID, "price").click()
        self.driver.find_element(By.ID, "price").send_keys("90")
        self.driver.find_element(By.ID, "manufacturer").click()
        dropdown = self.driver.find_element(By.ID, "manufacturer")
        dropdown.find_element(By.XPATH, "//option[. = 'Yamaha']").click()
        self.driver.find_element(By.CSS_SELECTOR, "#manufacturer > option:nth-child(4)").click()
        self.driver.find_element(By.ID, "part_1").click()
        self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(2) #part_2").click()
        self.driver.find_element(By.CSS_SELECTOR, "form .form-group:nth-child(2) > .form-check:nth-child(4)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(2) #part_3").click()
        self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(2) #part_6").click()
        self.driver.find_element(By.ID, "part_5").click()
        self.driver.find_element(By.ID, "part_8").click()
        self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(2) #part_10").click()
        self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(2) #part_12").click()
        self.driver.find_element(By.ID, "part_12").click()
        self.driver.find_element(By.ID, "part_16").click()
        self.driver.find_element(By.NAME, "ruedac").click()
        self.driver.find_element(By.NAME, "frenoc").click()
        self.driver.find_element(By.ID, "part_19").click()
        self.driver.find_element(By.ID, "part_23").click()
        self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(2) #part_23").click()
        self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(2) #part_26").click()
        self.driver.find_element(By.ID, "part_26").click()
        self.driver.find_element(By.CSS_SELECTOR, "div:nth-child(17) > .form-group:nth-child(1) > .form-check:nth-child(4)").click()
        self.driver.find_element(By.ID, "part_30").click()
        self.driver.find_element(By.CSS_SELECTOR, ".form-group:nth-child(2) #part_30").click()
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
        self.driver.find_element(By.LINK_TEXT, "Más detalles").click()
        self.driver.find_element(By.LINK_TEXT, "Editar motocicleta").click()
        self.driver.find_element(By.ID, "stock").click()
        self.driver.find_element(By.ID, "stock").send_keys("500")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
        self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(10) .hidden-sm").click()
        self.driver.find_element(By.LINK_TEXT, "Editar pieza").click()
        self.driver.find_element(By.ID, "stock").click()
        self.driver.find_element(By.ID, "stock").send_keys("10")
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
        self.driver.find_element(By.LINK_TEXT, "Bienvenido, Admin").click()
        self.driver.find_element(By.LINK_TEXT, "Administrar").click()
        self.driver.find_element(By.LINK_TEXT, "Administrar reclamaciones").click()
        self.driver.find_element(By.LINK_TEXT, "Responder").click()
        self.driver.find_element(By.NAME, "response_text").click()
        self.driver.find_element(By.NAME, "response_text").send_keys("Pues te aguantas")
        self.driver.find_element(By.CSS_SELECTOR, ".float-right").click()
        self.driver.find_element(By.LINK_TEXT, "Editar Respuesta").click()
        self.driver.find_element(By.NAME, "response_text").click()
        self.driver.find_element(By.NAME, "response_text").send_keys("Pues te aguantas 2")
        self.driver.find_element(By.CSS_SELECTOR, ".float-right").click()



       